<?php
declare(strict_types=1);

/** Buja Learn, the intermediate and advanced tiers. Merged into Curriculum::courses(). */
final class Curriculum2
{
    private static function q(string $q, array $opts, int $answer, string $why): array { return ['q' => $q, 'options' => $opts, 'answer' => $answer, 'why' => $why]; }

    public static function courses(): array
    {
        return [
            'frontend2' => ['title' => 'Frontend, Intermediate', 'track' => 'frontend', 'level' => 'Intermediate', 'hours' => 10, 'color' => '#FF7A1A', 'after' => 'frontend',
                'blurb' => 'Components without a framework, accessibility that real people depend on, performance on cheap phones, and the browser APIs that make a web app feel native.',
                'outcomes' => ['Build reusable components from plain functions', 'Make a page usable with a screen reader and a keyboard', 'Measure and cut load time on a slow connection', 'Use storage, history and the service worker like an app'],
                'lessons' => self::frontend2()],
            'frontend3' => ['title' => 'Frontend, Advanced', 'track' => 'frontend', 'level' => 'Advanced', 'hours' => 12, 'color' => '#FF7A1A', 'after' => 'frontend2',
                'blurb' => 'The engineering under a serious frontend: rendering from state with diffing, TypeScript-style thinking, async patterns that do not leak, testing, and offline-first design.',
                'outcomes' => ['Write a small virtual DOM and understand what React does', 'Cancel, debounce and retry async work correctly', 'Test frontend code without a browser', 'Design an offline-first app with sync'],
                'lessons' => self::frontend3()],
            'backend2' => ['title' => 'Backend, Intermediate', 'track' => 'backend', 'level' => 'Intermediate', 'hours' => 11, 'color' => '#2E7D1E', 'after' => 'backend',
                'blurb' => 'Schema design, migrations, transactions, indexes that actually help, pagination that scales, caching, and background work. The lessons a first production system teaches painfully.',
                'outcomes' => ['Design a schema that survives change', 'Use transactions and indexes correctly', 'Paginate with cursors, not offsets', 'Cache and queue work without losing data'],
                'lessons' => self::backend2()],
            'backend3' => ['title' => 'Backend, Advanced', 'track' => 'backend', 'level' => 'Advanced', 'hours' => 12, 'color' => '#2E7D1E', 'after' => 'backend2',
                'blurb' => 'Security in depth, idempotency, rate limiting, webhooks, observability, and the failure modes of distributed systems. What separates an API that works from one you can run for years.',
                'outcomes' => ['Threat-model an API and close the common holes', 'Make writes safe to retry', 'Consume and emit webhooks reliably', 'Instrument a service so you can debug it at 2am'],
                'lessons' => self::backend3()],
            'ai2' => ['title' => 'AI, Intermediate: Building with Models', 'track' => 'ai', 'level' => 'Intermediate', 'hours' => 10, 'color' => '#B7791F', 'after' => 'ai',
                'blurb' => 'Retrieval-augmented generation from scratch: chunking, embeddings, similarity search, grounding, and an evaluation harness so you know it works.',
                'outcomes' => ['Chunk documents for retrieval', 'Compute and compare embeddings', 'Ground answers in retrieved text and cite it', 'Build an evaluation set and measure changes'],
                'lessons' => self::ai2()],
            'ai3' => ['title' => 'AI, Advanced: Agents and Production', 'track' => 'ai', 'level' => 'Advanced', 'hours' => 10, 'color' => '#B7791F', 'after' => 'ai2',
                'blurb' => 'Tool use, agent loops, structured output at scale, guardrails, cost control and the operational habits of teams that ship AI features to real users.',
                'outcomes' => ['Give a model tools and run an agent loop safely', 'Enforce structured output with retries and validation', 'Design guardrails and test them', 'Run an AI feature within a budget'],
                'lessons' => self::ai3()],
        ];
    }

    /* ==================================================== FRONTEND 2 ==================================================== */
    private static function frontend2(): array
    {
        return [
            ['title' => 'Components without a framework', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>A component is a function that takes data and returns HTML. That is the whole idea, and you do not need React to use it.</p><pre>function JobCard({ title, district, pay }) {\n  return `&lt;div class=\"card\"&gt;&lt;h3&gt;\${esc(title)}&lt;/h3&gt;&lt;p&gt;\${esc(district)} · ₦\${pay.toLocaleString()}&lt;/p&gt;&lt;/div&gt;`;\n}\nlist.innerHTML = jobs.map(JobCard).join('');</pre><p>Two rules make this safe and composable. <strong>Escape everything</strong> that came from a user: <code>&lt;</code> becomes <code>&amp;lt;</code>, or a job titled <code>&lt;script&gt;</code> runs in every visitor's browser. And <strong>components call components</strong>: <code>JobList</code> maps over jobs and calls <code>JobCard</code>.</p><p><strong>Task:</strong> write <code>esc(s)</code> that escapes <code>&amp; &lt; &gt; \" '</code>. Write <code>JobCard(job)</code> returning a <code>div.card</code> with the title in an <code>h3</code>, escaped. Write <code>JobList(jobs)</code> that returns all cards joined, or <code>&lt;p class=\"empty\"&gt;No jobs yet&lt;/p&gt;</code> when the list is empty.</p>",
             'starter' => "function esc(s) {\n}\nfunction JobCard(job) {\n}\nfunction JobList(jobs) {\n}\n",
             'tests' => [['expr' => "esc('<b>&\"') === '&lt;b&gt;&amp;&quot;'", 'msg' => 'esc should escape < > & and quotes'], ['expr' => "JobCard({ title: 'Teller', district: 'Wuse', pay: 90000 }).includes('<h3>Teller</h3>')", 'msg' => 'JobCard puts the title in an h3'], ['expr' => "!JobCard({ title: '<script>x</script>', district: 'Wuse', pay: 1 }).includes('<script>')", 'msg' => 'A malicious title must be escaped'], ['expr' => "(JobList([{ title: 'A', district: 'W', pay: 1 }, { title: 'B', district: 'W', pay: 2 }]).match(/class=\"card\"/g) || []).length === 2", 'msg' => 'JobList renders one card per job'], ['expr' => "JobList([]).includes('class=\"empty\"')", 'msg' => 'An empty list shows the empty message']]],

            ['title' => 'Accessibility is not optional', 'kind' => 'code', 'lang' => 'html', 'minutes' => 14,
             'body' => "<p>Around one in ten people use the web with some assistance: a screen reader, a keyboard only, high zoom, or a slow connection. Building for them makes the app better for everyone, and in a city app for the public it is the job.</p><ul><li>Every <code>&lt;img&gt;</code> has <code>alt</code>. Every form control has a <code>&lt;label for&gt;</code>.</li><li>Buttons are <code>&lt;button&gt;</code>, links are <code>&lt;a href&gt;</code>. A clickable <code>div</code> is invisible to a keyboard.</li><li>Icon-only buttons need <code>aria-label</code>. Colour is never the only signal.</li><li>Focus is visible. Never <code>outline: none</code> without a replacement.</li><li>Headings are in order, one <code>h1</code>.</li></ul><p><strong>Task:</strong> fix the form. The input needs a label linked by <code>for</code>/<code>id</code>. The icon button needs an <code>aria-label</code>. The clickable div must become a real <code>button</code> with the class <code>menu</code>. The image needs alt text.</p>",
             'starter' => "<h1>Report a problem</h1>\n<input id=\"desc\" placeholder=\"Describe it\">\n<button>🔍</button>\n<div class=\"menu\" onclick=\"alert('menu')\">Menu</div>\n<img src=\"data:,\">\n",
             'tests' => [['sel' => 'label[for=desc]', 'msg' => 'Add a label linked to the input with for="desc"'], ['sel' => 'button[aria-label]', 'msg' => 'The icon button needs an aria-label'], ['sel' => 'button.menu', 'msg' => 'The menu must be a real button'], ['sel' => 'img[alt]', 'msg' => 'The image needs alt text'], ['sel' => 'h1', 'msg' => 'Keep the h1']]],

            ['title' => 'Performance on a cheap phone', 'kind' => 'read', 'minutes' => 10,
             'body' => "<p>Most of Abuja is on a ₦60,000 Android with a 3G-quality connection during the day. Your page has to work there, not on your laptop.</p><p><strong>Measure first.</strong> Chrome DevTools, Network tab, throttle to Slow 3G and a 4x CPU slowdown. Lighthouse gives you a score and a list. Buja's targets: first paint under 2 seconds on 3G, under 300 KB of JavaScript.</p><p><strong>Cut what you send.</strong> Images are the usual culprit: resize on the phone before upload (Buja does), serve WebP or JPEG at the size displayed, add <code>loading=\"lazy\"</code> below the fold. Split JavaScript so the home screen does not load the chat, the map and the editor.</p><p><strong>Do less on the main thread.</strong> Long loops block taps. Render in chunks with <code>requestAnimationFrame</code>, or move heavy work to a Web Worker. Avoid layout thrash: read all the sizes you need, then write.</p><p><strong>Cache aggressively.</strong> A service worker can serve the app shell instantly and update in the background, which is why Buja opens even offline.</p>",
             'check' => [self::q('Where should you test performance?', ['Your laptop on office wifi', 'A throttled slow-3G profile with CPU slowdown', 'Only in production'], 1, 'Test on what your users actually have.'), self::q('The biggest cause of slow pages is usually', ['CSS', 'Unoptimised images', 'HTML comments'], 1, 'Image bytes dwarf everything else.'), self::q('A loop over 20,000 items freezes taps. Fix?', ['Use var', 'Chunk the work or use a Web Worker', 'Add more CSS'], 1, 'Keep the main thread free for input.')]],

            ['title' => 'Debounce, throttle and the event loop', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>JavaScript runs one thing at a time. Timers, network replies and events wait in a queue until the current job finishes. That is the event loop, and it explains both why a heavy loop freezes the page and how these two tools work.</p><p><strong>Debounce</strong>: run the function only after the calls stop for a while. Search boxes: do not fetch on every keystroke, fetch 300 ms after the last one.</p><p><strong>Throttle</strong>: run at most once per interval. Scroll handlers: update the map position at most every 100 ms.</p><pre>function debounce(fn, ms) {\n  let t;\n  return (...args) =&gt; { clearTimeout(t); t = setTimeout(() =&gt; fn(...args), ms); };\n}</pre><p><strong>Task:</strong> implement <code>debounce(fn, ms)</code> and <code>throttle(fn, ms)</code>. Debounce: only the last of a burst of calls runs, after <code>ms</code> of quiet, with the last arguments. Throttle: the first call runs immediately, further calls within <code>ms</code> are dropped.</p>",
             'starter' => "function debounce(fn, ms) {\n}\nfunction throttle(fn, ms) {\n}\n",
             'tests' => [['expr' => "(async () => { let n = 0, last; const d = debounce((x) => { n++; last = x; }, 50); d(1); d(2); d(3); await new Promise(r => setTimeout(r, 120)); return n === 1 && last === 3; })()", 'msg' => 'Debounce runs once, after the burst, with the last argument'], ['expr' => "(async () => { let n = 0; const t = throttle(() => n++, 50); t(); t(); t(); await new Promise(r => setTimeout(r, 80)); t(); return n === 2; })()", 'msg' => 'Throttle runs immediately, drops calls inside the window, allows one after']]],

            ['title' => 'Browser APIs: storage, history, sharing', 'kind' => 'code', 'lang' => 'js', 'minutes' => 12,
             'body' => "<p>The browser gives you most of what a native app has. Four you will use constantly:</p><ul><li><code>localStorage</code> keeps small strings across visits. Wrap it: it throws in private mode and only stores strings.</li><li><code>history.pushState</code> and the <code>popstate</code> event let a single page have real back-button behaviour. Buja uses the hash for the same reason.</li><li><code>navigator.share</code> opens the phone's share sheet; check it exists first.</li><li><code>IntersectionObserver</code> tells you when an element scrolls into view: lazy loading, infinite scroll.</li></ul><p><strong>Task:</strong> write <code>store</code> with <code>get(key, fallback)</code> and <code>set(key, value)</code> that JSON-encode values and never throw (return the fallback on any error). The <code>localStorage</code> here is simulated and throws on keys starting with <code>bad</code>.</p>",
             'starter' => "const store = {\n  get(key, fallback) {\n  },\n  set(key, value) {\n  },\n};\n",
             'setup' => "(function(){ const m = {}; Object.defineProperty(window, 'localStorage', { configurable: true, value: { getItem: (k) => { if (String(k).startsWith('bad')) throw new Error('blocked'); return k in m ? m[k] : null; }, setItem: (k, v) => { if (String(k).startsWith('bad')) throw new Error('blocked'); m[k] = String(v); }, removeItem: (k) => { delete m[k]; } } }); })();",
             'tests' => [['expr' => "(store.set('prefs', { dark: true, n: 3 }), store.get('prefs').n === 3 && store.get('prefs').dark === true)", 'msg' => 'set then get should round-trip an object'], ['expr' => "store.get('missing', 'none') === 'none'", 'msg' => 'A missing key returns the fallback'], ['expr' => "store.get('bad-key', 'safe') === 'safe'", 'msg' => 'An error while reading returns the fallback instead of throwing'], ['expr' => "(function(){ try { store.set('bad-key', 1); return true; } catch { return false; } })()", 'msg' => 'An error while writing must not throw']]],

            ['title' => 'Project: an installable offline page', 'kind' => 'quiz', 'minutes' => 10,
             'body' => "<p>A progressive web app is a page plus a manifest plus a service worker. The manifest names it and gives it an icon; the service worker caches the shell so it opens with no network. Buja is one, which is why it installs from Chrome without an app store.</p><p>The service worker rules that matter: cache the shell on install, serve it from cache first, update in the background, bump a version string to invalidate. Never cache API responses you cannot afford to be stale.</p>",
             'check' => [self::q('What makes a page installable?', ['A big download button', 'A manifest and a service worker over HTTPS', 'An app store listing'], 1, 'Those three, plus an icon, and Chrome offers Install.'), self::q('You changed app.js but users still see the old one.', ['Tell them to clear cache', 'Bump the service worker version so the old cache is dropped', 'Rename the site'], 1, 'Versioned caches are how updates reach installed apps.'), self::q('Should the service worker cache POST responses?', ['Yes, everything', 'No; cache the shell, not writes or live data', 'Only on iPhone'], 1, 'Stale writes cause real bugs.'), self::q('The app opens offline but shows old data. Is that a bug?', ['Yes, always', 'No, if it says the data is old and refreshes when online', 'Only for chat'], 1, 'Honest staleness beats a blank screen.')]],
        ];
    }

    /* ==================================================== FRONTEND 3 ==================================================== */
    private static function frontend3(): array
    {
        return [
            ['title' => 'Render from state: a tiny virtual DOM', 'kind' => 'code', 'lang' => 'js', 'minutes' => 18,
             'body' => "<p>Frameworks do one clever thing: describe the UI as data, compare the new description with the old, and touch the real DOM only where they differ. Here is the idea in miniature.</p><pre>const tree = { tag: 'ul', children: [ { tag: 'li', text: 'Wuse' }, { tag: 'li', text: 'Garki' } ] };</pre><p><strong>Task:</strong> write <code>create(node)</code> that turns such a tree into a real element (a node with <code>text</code> becomes an element containing that text; <code>children</code> are created recursively). Then <code>patch(parent, oldTree, newTree)</code> that updates <code>parent.firstChild</code> in place: if the tags differ, replace the whole element; if both have text and it changed, update <code>textContent</code> only; otherwise patch children pairwise, appending or removing extras. Count how many times you create elements to prove you are not rebuilding everything.</p>",
             'starter' => "let creates = 0;\nfunction create(node) {\n  creates++;\n  const el = document.createElement(node.tag);\n  if (node.text != null) el.textContent = node.text;\n  (node.children || []).forEach((c) => el.appendChild(create(c)));\n  return el;\n}\nfunction patch(parent, oldT, newT) {\n  // parent.firstChild is the element made from oldT; make it match newT with as few changes as possible\n}\n",
             'tests' => [['expr' => "(function(){ const p = document.createElement('div'); const t1 = { tag: 'ul', children: [{ tag: 'li', text: 'Wuse' }, { tag: 'li', text: 'Garki' }] }; p.appendChild(create(t1)); creates = 0; const t2 = { tag: 'ul', children: [{ tag: 'li', text: 'Wuse' }, { tag: 'li', text: 'Jabi' }] }; patch(p, t1, t2); window.__p = p; return p.querySelectorAll('li')[1].textContent === 'Jabi' && creates === 0; })()", 'msg' => 'Changing one text should update it without creating elements'], ['expr' => "(function(){ const p = window.__p; const t2 = { tag: 'ul', children: [{ tag: 'li', text: 'Wuse' }, { tag: 'li', text: 'Jabi' }] }; const t3 = { tag: 'ul', children: [{ tag: 'li', text: 'Wuse' }, { tag: 'li', text: 'Jabi' }, { tag: 'li', text: 'Kubwa' }] }; creates = 0; patch(p, t2, t3); return p.querySelectorAll('li').length === 3 && creates === 1; })()", 'msg' => 'Adding a child should create exactly one element'], ['expr' => "(function(){ const p = window.__p; const t3 = { tag: 'ul', children: [{ tag: 'li', text: 'Wuse' }, { tag: 'li', text: 'Jabi' }, { tag: 'li', text: 'Kubwa' }] }; const t4 = { tag: 'ol', children: [{ tag: 'li', text: 'One' }] }; patch(p, t3, t4); return p.firstChild.tagName === 'OL' && p.querySelectorAll('li').length === 1; })()", 'msg' => 'A different tag replaces the element']]],

            ['title' => 'Types without a compiler', 'kind' => 'read', 'minutes' => 10,
             'body' => "<p>TypeScript adds types to JavaScript and catches whole classes of bugs before you run anything. You will meet it on any serious team. The mindset matters more than the syntax, and you can adopt it today.</p><pre>// TypeScript\nfunction fareFor(km: number): number { ... }\ntype Job = { id: number; title: string; pay?: number };</pre><p>The habits: every function has a clear input shape and output shape, written down; optional fields are marked and handled; you never pass \"whatever came from the API\" straight through, you validate it at the edge into a known shape. JSDoc comments give you most of the benefit in plain JavaScript, and editors read them:</p><pre>/** @param {number} km @returns {number} */\nfunction fareFor(km) { ... }</pre><p>Where types earn their keep: refactoring (rename a field and every use lights up), API boundaries, and code you will not touch for six months.</p>",
             'check' => [self::q('What does a type system catch?', ['Slow code', 'Passing the wrong shape of data before the code runs', 'Bad design'], 1, 'Shape mistakes, at edit time.'), self::q('Data arrives from an API. What do you do with it?', ['Use it directly; it is JSON', 'Validate it into a known shape at the edge', 'Log it'], 1, 'The edge is where unknown becomes known.'), self::q('Cheapest way to get type help in plain JS?', ['Rewrite in Rust', 'JSDoc comments the editor understands', 'Longer variable names'], 1, 'JSDoc gives editors and tools the shapes.')]],

            ['title' => 'Async that does not leak', 'kind' => 'code', 'lang' => 'js', 'minutes' => 16,
             'body' => "<p>Three async bugs appear in every app. A search fires two requests and the slower one arrives last, overwriting the right answer. A user navigates away while a request is in flight and the callback touches a screen that no longer exists. A flaky network needs a retry, but not forever.</p><p>Tools: <code>AbortController</code> cancels a fetch; a request counter or token ignores stale replies; retries use exponential backoff with a cap.</p><p><strong>Task:</strong> <code>latest(fn)</code> wraps an async function so only the most recent call's result is delivered: earlier calls resolve to <code>undefined</code> when a newer call has started. <code>retry(fn, times, delayMs)</code> calls <code>fn</code>, and on rejection waits <code>delayMs</code>, doubles it, and tries again up to <code>times</code> total attempts before rethrowing the last error.</p>",
             'starter' => "function latest(fn) {\n}\nasync function retry(fn, times, delayMs) {\n}\n",
             'tests' => [['expr' => "(async () => { const slow = (ms, v) => new Promise(r => setTimeout(() => r(v), ms)); const l = latest((ms, v) => slow(ms, v)); const a = l(80, 'old'); const b = l(20, 'new'); const [ra, rb] = await Promise.all([a, b]); return ra === undefined && rb === 'new'; })()", 'msg' => 'latest: the older call is ignored, the newer wins'], ['expr' => "(async () => { let n = 0; const v = await retry(async () => { n++; if (n < 3) throw new Error('flaky'); return 'ok'; }, 5, 5); return v === 'ok' && n === 3; })()", 'msg' => 'retry: succeeds on the third attempt'], ['expr' => "(async () => { let n = 0; try { await retry(async () => { n++; throw new Error('down'); }, 3, 5); return false; } catch (e) { return n === 3 && e.message === 'down'; } })()", 'msg' => 'retry: gives up after the allowed attempts with the last error']]],

            ['title' => 'Testing frontend code', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>Untested frontend code is where regressions hide. You do not need a framework to start: a test is a function that calls your code and throws if the result is wrong. Pure functions (formatting, filtering, state changes) are the easiest and most valuable to test.</p><pre>function test(name, fn) { try { fn(); passed.push(name); } catch (e) { failed.push(name + ': ' + e.message); } }\nfunction expect(actual) { return { toBe(v) { if (actual !== v) throw new Error(`expected \${v}, got \${actual}`); } }; }</pre><p>The habit: when you fix a bug, first write the test that would have caught it, watch it fail, then fix. Now it can never come back silently.</p><p><strong>Task:</strong> build a tiny runner. <code>test(name, fn)</code> records passes and failures. <code>expect(actual)</code> returns an object with <code>toBe(v)</code> (strict equal), <code>toEqual(v)</code> (deep equal via JSON) and <code>toThrow()</code> (actual is a function that must throw). Then use it to write three tests for <code>fareFor</code> below, including one that fails on purpose to show the runner reports it.</p>",
             'starter' => "const passed = [], failed = [];\nfunction test(name, fn) {\n}\nfunction expect(actual) {\n}\n\nfunction fareFor(km) { return km <= 2 ? 100 : 100 + (km - 2) * 50; }\n\n// write tests here; make one fail deliberately\n",
             'tests' => [['expr' => "(function(){ test('t', () => expect(1 + 1).toBe(2)); return passed.includes('t'); })()", 'msg' => 'toBe passes on equal values'], ['expr' => "(function(){ test('u', () => expect({ a: 1 }).toEqual({ a: 1 })); return passed.includes('u'); })()", 'msg' => 'toEqual compares structure'], ['expr' => "(function(){ test('v', () => expect(() => { throw new Error('x'); }).toThrow()); return passed.includes('v'); })()", 'msg' => 'toThrow passes when the function throws'], ['expr' => "(function(){ test('w', () => expect(2).toBe(3)); return failed.some(f => f.startsWith('w')); })()", 'msg' => 'A wrong expectation is recorded as a failure with its name'], ['expr' => "failed.length >= 2 && passed.length >= 5", 'msg' => 'You wrote tests for fareFor, including one that fails on purpose']]],

            ['title' => 'Offline-first and sync', 'kind' => 'read', 'minutes' => 12,
             'body' => "<p>Offline-first means the app works from local data and treats the network as an optimisation. On a Nyanya bus at 7am that is the difference between an app people use and one they uninstall.</p><p><strong>Reads</strong>: keep a local copy (IndexedDB for anything bigger than a few KB), render from it instantly, refresh from the server when online, and show how old the data is.</p><p><strong>Writes</strong>: queue them locally with a client-generated id, show them as pending, send when online, mark confirmed when the server replies. If the server rejects one, show it and let the user fix it. Buja's Trip Share pings work this way.</p><p><strong>Conflicts</strong>: two edits to the same thing while offline. Options: last write wins (simple, loses data), server wins with the client shown the difference, or merge by field. Pick deliberately; most apps get away with last-write-wins for personal data and server-wins for shared data.</p><p><strong>Idempotency</strong>: a queued write may be sent twice after a crash. Give every write a unique id and have the server ignore repeats. That single habit prevents the double-post bugs that plague chat apps.</p>",
             'check' => [self::q('A write is made offline. What does the user see?', ['Nothing until online', 'It appears immediately, marked pending, then confirmed', 'An error'], 1, 'Optimistic, honest about state.'), self::q('Why give every queued write a unique id?', ['For sorting', 'So the server can ignore a duplicate after a retry', 'For analytics'], 1, 'Idempotency is what makes retries safe.'), self::q('Two people edit a shared post offline. Reasonable default?', ['Delete both', 'Server wins, show the loser the difference', 'Random'], 1, 'Shared data should not silently lose someone\'s work.'), self::q('Where do you keep a large local dataset?', ['localStorage', 'IndexedDB', 'A cookie'], 1, 'localStorage is small and synchronous; IndexedDB is built for this.')]],

            ['title' => 'Capstone: an event emitter and a store', 'kind' => 'code', 'lang' => 'js', 'minutes' => 20,
             'body' => "<p>Two building blocks every larger frontend has, from scratch.</p><p><strong>Emitter</strong>: <code>on(event, fn)</code> returns an unsubscribe function; <code>emit(event, ...args)</code> calls every listener; <code>once(event, fn)</code> listens one time.</p><p><strong>Store</strong>: <code>createStore(reducer, initial)</code> returns <code>{ getState, dispatch, subscribe }</code>. <code>dispatch(action)</code> computes the new state with the reducer and notifies subscribers; <code>subscribe(fn)</code> returns an unsubscribe. This is Redux in twenty lines, and once you have written it you understand every state library.</p>",
             'starter' => "function createEmitter() {\n}\nfunction createStore(reducer, initial) {\n}\n\nconst reducer = (state, action) => {\n  if (action.type === 'add') return { ...state, items: [...state.items, action.item] };\n  if (action.type === 'clear') return { ...state, items: [] };\n  return state;\n};\n",
             'tests' => [['expr' => "(function(){ const e = createEmitter(); let n = 0; const off = e.on('x', (v) => { n += v; }); e.emit('x', 2); off(); e.emit('x', 5); return n === 2; })()", 'msg' => 'on returns an unsubscribe that works'], ['expr' => "(function(){ const e = createEmitter(); let n = 0; e.once('y', () => n++); e.emit('y'); e.emit('y'); return n === 1; })()", 'msg' => 'once fires a single time'], ['expr' => "(function(){ const s = createStore(reducer, { items: [] }); s.dispatch({ type: 'add', item: 'a' }); s.dispatch({ type: 'add', item: 'b' }); return s.getState().items.length === 2; })()", 'msg' => 'dispatch runs the reducer'], ['expr' => "(function(){ const s = createStore(reducer, { items: [] }); let seen = 0; const off = s.subscribe(() => seen++); s.dispatch({ type: 'add', item: 'a' }); off(); s.dispatch({ type: 'clear' }); return seen === 1 && s.getState().items.length === 0; })()", 'msg' => 'subscribers are notified and can unsubscribe']]],
        ];
    }

    /* ==================================================== BACKEND 2 ==================================================== */
    private static function backend2(): array
    {
        return [
            ['title' => 'Schema design that survives change', 'kind' => 'read', 'minutes' => 12,
             'body' => "<p>The database outlives every version of your code. Design it for the questions you will ask, and for the changes you cannot predict.</p><ul><li><strong>One fact in one place.</strong> A user's district lives in <code>users</code>, not copied into every job row. Copies drift.</li><li><strong>Ids are meaningless.</strong> Auto-increment integers or random ids. Never a phone number or email as a primary key; people change them.</li><li><strong>Every table has <code>created_at</code></strong>, and anything that changes has <code>updated_at</code>. You will thank yourself.</li><li><strong>Soft delete</strong> with <code>deleted_at</code> for anything a person made. Hard delete only for junk.</li><li><strong>Constraints are code.</strong> <code>NOT NULL</code>, <code>UNIQUE</code>, foreign keys. The database enforcing a rule beats every app enforcing it.</li><li><strong>Enums for small fixed sets</strong>, a lookup table when the set will grow or needs attributes.</li></ul><p><strong>Migrations</strong>: every schema change is a numbered file that runs once, forward only, in every environment in the same order. Adding a column is safe; renaming one is two migrations (add new, backfill, switch code, drop old) so the app never breaks mid-deploy.</p>",
             'check' => [self::q('Best primary key for users?', ['Email', 'Phone number', 'A meaningless id'], 2, 'Emails and phones change; ids do not.'), self::q('You need to rename a column that live code uses.', ['Rename it in one migration', 'Add the new column, backfill, switch code, drop the old one later', 'Never rename'], 1, 'Two-step changes keep the app up during deploy.'), self::q('Where should the rule \"a job must have a company\" live?', ['Only in the app', 'As a NOT NULL foreign key in the database, and in the app', 'In documentation'], 1, 'The database is the last line of defence.')]],

            ['title' => 'Transactions and indexes', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>A <strong>transaction</strong> makes several writes succeed or fail together. Buying a ticket is two writes: insert the ticket, reduce the seats. Without a transaction, a crash between them sells a seat that was never recorded.</p><p>An <strong>index</strong> is a sorted copy of one or more columns that turns a scan into a lookup. Add them on columns in <code>WHERE</code>, <code>JOIN</code> and <code>ORDER BY</code>. Every index slows writes slightly, so do not index everything. A composite index <code>(district, created_at)</code> serves \"jobs in Lugbe, newest first\" in one step; <code>(created_at, district)</code> does not, because the leading column must match the filter.</p><p><strong>Task:</strong> simulate a transaction. <code>db</code> has <code>seats</code> and <code>tickets</code>. Write <code>buy(db, qty)</code>: if <code>qty</code> exceeds <code>db.seats</code>, throw and leave <code>db</code> untouched; otherwise reduce seats and push a ticket, but do it so that if <code>db.audit(...)</code> throws midway, <em>nothing</em> changes (copy, mutate the copy, commit by assigning back).</p>",
             'starter' => "function buy(db, qty) {\n  // all or nothing: seats down, ticket in, audit written; any failure leaves db exactly as it was\n}\n",
             'setup' => "window.makeDb = (seats, auditFails) => ({ seats, tickets: [], log: [], audit(msg) { if (auditFails) throw new Error('audit down'); this.log.push(msg); } });",
             'tests' => [['expr' => "(function(){ const db = makeDb(5, false); buy(db, 2); return db.seats === 3 && db.tickets.length === 1 && db.log.length === 1; })()", 'msg' => 'A normal purchase commits all three changes'], ['expr' => "(function(){ const db = makeDb(1, false); try { buy(db, 2); return false; } catch { return db.seats === 1 && db.tickets.length === 0; } })()", 'msg' => 'Not enough seats: throws and changes nothing'], ['expr' => "(function(){ const db = makeDb(5, true); try { buy(db, 2); return false; } catch { return db.seats === 5 && db.tickets.length === 0 && db.log.length === 0; } })()", 'msg' => 'If the audit fails midway, seats and tickets roll back too']]],

            ['title' => 'Pagination that scales', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p><code>OFFSET 10000 LIMIT 20</code> makes the database read 10,020 rows to return 20. It also skips or repeats items when rows are inserted between pages. <strong>Cursor pagination</strong> fixes both: sort by a unique, sequential key and ask for rows after the last one you saw.</p><pre>SELECT * FROM jobs WHERE id &lt; ? ORDER BY id DESC LIMIT 20;   -- ? is the last id from the previous page</pre><p>The API returns the items plus a <code>nextCursor</code>, an opaque string the client hands back. Encode it (base64 of the id, or of several fields) so clients do not build cursors by hand.</p><p><strong>Task:</strong> <code>page(rows, cursor, limit)</code>. <code>rows</code> are sorted by <code>id</code> descending. With no cursor, return the first <code>limit</code> rows. With a cursor (base64 of an id), return rows with id below it. Return <code>{ items, nextCursor }</code> where <code>nextCursor</code> is the base64 id of the last item, or <code>null</code> when there are no more rows after this page.</p>",
             'starter' => "function encode(id) { return btoa(String(id)); }\nfunction decode(c) { return Number(atob(c)); }\n\nfunction page(rows, cursor, limit) {\n}\n",
             'setup' => "window.rows = Array.from({ length: 45 }, (_, i) => ({ id: 45 - i, title: 'Job ' + (45 - i) }));",
             'tests' => [['expr' => "(function(){ const p = page(rows, null, 20); return p.items.length === 20 && p.items[0].id === 45 && p.nextCursor === btoa('26'); })()", 'msg' => 'First page: 20 items from 45 down, cursor points at id 26'], ['expr' => "(function(){ const p1 = page(rows, null, 20); const p2 = page(rows, p1.nextCursor, 20); return p2.items[0].id === 25 && p2.items.length === 20; })()", 'msg' => 'Second page continues from 25'], ['expr' => "(function(){ const p3 = page(rows, btoa('6'), 20); return p3.items.length === 5 && p3.nextCursor === null; })()", 'msg' => 'Last page returns the remainder and a null cursor']]],

            ['title' => 'Caching without lying', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>Caching is remembering an answer so you do not compute it again. The two hard problems: when to throw the memory away, and how big to let it grow.</p><p><strong>TTL</strong> (time to live): an entry expires after N seconds. Weather, exchange rates, a directory that changes hourly. Buja caches the weather for 40 minutes.</p><p><strong>LRU</strong> (least recently used): when the cache is full, evict the entry nobody has touched for longest. Bounded memory.</p><p><strong>Invalidate on write</strong>: when the thing changes, delete its cache entry, or the cache serves a lie. The rule: whoever writes the data owns clearing the cache.</p><p><strong>Task:</strong> <code>createCache(max, ttlMs, now)</code> where <code>now()</code> returns the current time (injected so tests can control it). <code>get(key)</code> returns the value or <code>undefined</code> if missing or expired, and marks the key as recently used. <code>set(key, value)</code> stores with the current time, evicting the least recently used entry when over <code>max</code>. <code>del(key)</code> removes. <code>size()</code> counts live entries.</p>",
             'starter' => "function createCache(max, ttlMs, now) {\n}\n",
             'tests' => [['expr' => "(function(){ let t = 0; const c = createCache(2, 1000, () => t); c.set('a', 1); c.set('b', 2); return c.get('a') === 1 && c.size() === 2; })()", 'msg' => 'set and get work'], ['expr' => "(function(){ let t = 0; const c = createCache(2, 1000, () => t); c.set('a', 1); c.set('b', 2); c.get('a'); c.set('c', 3); return c.get('b') === undefined && c.get('a') === 1 && c.get('c') === 3; })()", 'msg' => 'Over capacity, the least recently used entry (b) is evicted'], ['expr' => "(function(){ let t = 0; const c = createCache(5, 1000, () => t); c.set('w', 'sunny'); t = 1500; return c.get('w') === undefined; })()", 'msg' => 'Entries expire after the TTL'], ['expr' => "(function(){ let t = 0; const c = createCache(5, 1000, () => t); c.set('k', 1); c.del('k'); return c.get('k') === undefined && c.size() === 0; })()", 'msg' => 'del removes an entry']]],

            ['title' => 'Background work and queues', 'kind' => 'read', 'minutes' => 10,
             'body' => "<p>Some work should not happen inside a request: sending 300 push notifications, resizing a video, calling a slow third party. Do it later, in the background, from a queue.</p><p>The pattern: the request writes a job row (<code>type</code>, <code>payload</code>, <code>run_at</code>, <code>attempts</code>, <code>status</code>) and returns immediately. A worker loop picks due jobs, runs them, marks them done or schedules a retry with backoff. Buja's digest works this way, five people per tick.</p><p>Rules that keep queues honest: jobs are <strong>idempotent</strong> (running twice is harmless, because they will run twice eventually); a job that fails N times goes to a dead-letter list a human looks at; workers lock a job before running it so two workers do not both take it; and the payload contains ids, not copies of data, so the worker reads fresh state.</p><p>On a free host without a worker process, the trick is to run the loop off ordinary traffic in small bounded batches, which Buja does, or use a scheduler to hit an endpoint.</p>",
             'check' => [self::q('A request needs to send 300 notifications. Where?', ['Inside the request', 'In a background job', 'On the client'], 1, 'Requests should return fast; fan-out belongs in a queue.'), self::q('Why must jobs be idempotent?', ['For speed', 'Because retries and crashes will run some of them twice', 'They do not need to be'], 1, 'Assume at-least-once delivery.'), self::q('A job has failed five times.', ['Retry forever', 'Move it to a dead-letter list for a person to inspect', 'Delete it'], 1, 'Infinite retries hide problems and burn resources.')]],

            ['title' => 'Capstone: a job queue', 'kind' => 'code', 'lang' => 'js', 'minutes' => 20,
             'body' => "<p>Build the queue from the previous lesson, in memory.</p><ul><li><code>enqueue(type, payload, runAt = 0)</code> adds a job with <code>attempts: 0</code>, <code>status: 'pending'</code> and returns its id.</li><li><code>register(type, handler)</code> maps a type to an async handler.</li><li><code>tick(now)</code> runs every pending job whose <code>runAt &lt;= now</code>, one at a time. On success mark <code>done</code>. On failure increment <code>attempts</code>; if under 3, set <code>runAt = now + 1000 * 2^attempts</code> and leave pending; else mark <code>dead</code> with the error message.</li><li><code>stats()</code> returns counts by status.</li></ul>",
             'starter' => "const jobs = []; const handlers = {}; let nextId = 1;\nfunction enqueue(type, payload, runAt = 0) {\n}\nfunction register(type, handler) {\n}\nasync function tick(now) {\n}\nfunction stats() {\n}\n",
             'tests' => [['expr' => "(async () => { let sent = []; register('push', async (p) => { sent.push(p.to); }); enqueue('push', { to: 'ada' }); enqueue('push', { to: 'bola' }, 5000); await tick(0); return sent.length === 1 && stats().done === 1 && stats().pending === 1; })()", 'msg' => 'tick runs due jobs only and marks them done'], ['expr' => "(async () => { let n = 0; register('flaky', async () => { n++; throw new Error('boom'); }); const id = enqueue('flaky', {}); await tick(0); const j = jobs.find(x => x.id === id); return j.status === 'pending' && j.attempts === 1 && j.runAt === 2000; })()", 'msg' => 'A failure schedules a retry with backoff (2000 ms after the first)'], ['expr' => "(async () => { const j = jobs.find(x => x.type === 'flaky'); await tick(2000); await tick(10000); return j.status === 'dead' && j.attempts === 3 && /boom/.test(j.error || ''); })()", 'msg' => 'After three failures the job is dead with its error'], ['expr' => "(async () => { await tick(5000); return stats().done === 2; })()", 'msg' => 'The delayed job runs once its time comes']]],
        ];
    }

    /* ==================================================== BACKEND 3 ==================================================== */
    private static function backend3(): array
    {
        return [
            ['title' => 'Threat-modelling an API', 'kind' => 'read', 'minutes' => 12,
             'body' => "<p>Before you defend, ask who attacks and how. For a city app: a scraper harvesting phone numbers, a scammer posting fake flats, a bored teenager with a script, and occasionally someone targeted. Each wants something different.</p><p>The list you check every endpoint against:</p><ul><li><strong>Authentication</strong>: who is this? Tokens expire and rotate.</li><li><strong>Authorisation</strong>: may <em>this</em> user do <em>this</em> to <em>this</em> object? The most common hole is checking the first and forgetting the third: \"GET /threads/12\" with no check that you are in thread 12.</li><li><strong>Input</strong>: length, type, range, encoding. Parameterised SQL. Escape output.</li><li><strong>Rate</strong>: per user and per address, tighter on sign-in, search and anything that sends email or SMS.</li><li><strong>Secrets</strong>: never in Git, never in logs, never in error messages.</li><li><strong>Uploads</strong>: check the bytes not the extension, cap the size, never execute.</li></ul><p>And the one habit that catches the rest: <strong>log who did what</strong>, and read the logs.</p>",
             'check' => [self::q('GET /threads/12 checks the user is signed in and returns the thread. What is missing?', ['Nothing', 'A check that this user is a member of thread 12', 'Caching'], 1, 'Authorisation on the object, not just authentication.'), self::q('A file upload named photo.jpg is actually a PHP script.', ['Trust the name', 'Check the bytes and never execute uploads', 'Rename it'], 1, 'Buja sniffs magic bytes for this reason.'), self::q('Where must secrets never appear?', ['Environment variables', 'Git, logs and error messages', 'The server'], 1, 'Any of those three leaks to more people than you think.')]],

            ['title' => 'Idempotent writes', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>Networks drop responses. The client sent \"pay ₦5,000\", the server did it, the reply was lost, the client retries, the server does it again. Idempotency keys fix this: the client sends a unique key with the write; the server stores the result under that key and returns the same result for any repeat.</p><p><strong>Task:</strong> <code>createIdempotent(handler)</code> returns a function <code>(key, body)</code>. The first call with a key runs <code>handler(body)</code>, stores its result, and returns it. Any later call with the same key returns the stored result without calling the handler, even if the body differs. Calls with no key always run the handler. Results are stored even when the handler throws: the same key rethrows the same error.</p>",
             'starter' => "function createIdempotent(handler) {\n}\n",
             'tests' => [['expr' => "(async () => { let n = 0; const pay = createIdempotent(async (b) => { n++; return { charged: b.amount, id: n }; }); const a = await pay('k1', { amount: 5000 }); const b = await pay('k1', { amount: 9999 }); return n === 1 && a.id === b.id && b.charged === 5000; })()", 'msg' => 'A repeat with the same key returns the first result and does not run again'], ['expr' => "(async () => { let n = 0; const pay = createIdempotent(async () => { n++; return n; }); await pay(null, {}); await pay(undefined, {}); return n === 2; })()", 'msg' => 'Without a key every call runs'], ['expr' => "(async () => { let n = 0; const f = createIdempotent(async () => { n++; throw new Error('declined'); }); let e1, e2; try { await f('k2', {}); } catch (e) { e1 = e.message; } try { await f('k2', {}); } catch (e) { e2 = e.message; } return n === 1 && e1 === 'declined' && e2 === 'declined'; })()", 'msg' => 'A failure is remembered too: the same key rethrows without re-running']]],

            ['title' => 'Rate limiting done properly', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>A fixed window (\"100 per minute\") lets a client send 100 at 11:59:59 and 100 more at 12:00:00. A <strong>token bucket</strong> is smoother: the bucket holds up to <code>capacity</code> tokens and refills at <code>rate</code> per second; each request takes one; when the bucket is empty, the request is refused. Bursts are allowed up to the capacity, the long-run rate is enforced, and the maths is three lines.</p><p><strong>Task:</strong> <code>createLimiter(capacity, ratePerSec, now)</code> with <code>allow(key)</code>: one bucket per key, starts full, refills continuously based on elapsed time from the injected <code>now()</code> (milliseconds), returns <code>true</code> and takes a token, or <code>false</code> when empty. Never exceed capacity when refilling.</p>",
             'starter' => "function createLimiter(capacity, ratePerSec, now) {\n}\n",
             'tests' => [['expr' => "(function(){ let t = 0; const l = createLimiter(3, 1, () => t); const r = [l.allow('a'), l.allow('a'), l.allow('a'), l.allow('a')]; return JSON.stringify(r) === '[true,true,true,false]'; })()", 'msg' => 'A full bucket allows the capacity, then refuses'], ['expr' => "(function(){ let t = 0; const l = createLimiter(3, 1, () => t); l.allow('b'); l.allow('b'); l.allow('b'); t = 1000; return l.allow('b') === true && l.allow('b') === false; })()", 'msg' => 'After one second at 1/s, exactly one more is allowed'], ['expr' => "(function(){ let t = 0; const l = createLimiter(2, 10, () => t); l.allow('c'); l.allow('c'); t = 60000; return l.allow('c') && l.allow('c') && !l.allow('c'); })()", 'msg' => 'Refill never exceeds capacity'], ['expr' => "(function(){ let t = 0; const l = createLimiter(1, 1, () => t); l.allow('x'); return l.allow('y') === true; })()", 'msg' => 'Buckets are per key']]],

            ['title' => 'Webhooks in and out', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>A webhook is a request another system sends you when something happens: Paystack saying a payment succeeded. Three rules for receiving them:</p><ol><li><strong>Verify the signature.</strong> The sender signs the body with a shared secret (HMAC). Anyone can POST to your URL; only the real sender can sign.</li><li><strong>Acknowledge fast, process later.</strong> Return 200 within seconds, queue the work. Senders retry on timeouts, which brings us to:</li><li><strong>Deduplicate.</strong> The same event will arrive twice. Store the event id; ignore repeats.</li></ol><p>Sending webhooks: sign the body, retry with backoff, give up after a day, and let the receiver see their delivery log.</p><p><strong>Task:</strong> <code>verify(body, signature, secret)</code> returns true when <code>signature</code> equals <code>hmac(secret, body)</code> (a simulated <code>hmac</code> is provided). <code>receive(event)</code> returns <code>'ignored'</code> for an invalid signature, <code>'duplicate'</code> for an event id seen before, and <code>'queued'</code> after pushing the event to <code>queue</code>.</p>",
             'starter' => "const seen = new Set(); const queue = [];\nfunction verify(body, signature, secret) {\n}\nfunction receive(event) {\n  // event: { id, body, signature }; the secret is SECRET\n}\n",
             'setup' => "window.SECRET = 's3cret'; window.hmac = (secret, body) => { let h = 0; const s = secret + '|' + body; for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0; return 'sig_' + h.toString(16); };",
             'tests' => [['expr' => "verify('{\"a\":1}', hmac(SECRET, '{\"a\":1}'), SECRET) === true && verify('{\"a\":1}', 'sig_nope', SECRET) === false", 'msg' => 'verify accepts a good signature and rejects a bad one'], ['expr' => "receive({ id: 'evt_1', body: '{\"paid\":true}', signature: hmac(SECRET, '{\"paid\":true}') }) === 'queued' && queue.length === 1", 'msg' => 'A valid new event is queued'], ['expr' => "receive({ id: 'evt_1', body: '{\"paid\":true}', signature: hmac(SECRET, '{\"paid\":true}') }) === 'duplicate' && queue.length === 1", 'msg' => 'The same event again is a duplicate, not queued twice'], ['expr' => "receive({ id: 'evt_2', body: '{\"paid\":true}', signature: 'sig_forged' }) === 'ignored' && queue.length === 1", 'msg' => 'A forged signature is ignored']]],

            ['title' => 'Observability: logs, metrics, traces', 'kind' => 'read', 'minutes' => 10,
             'body' => "<p>When something breaks at 2am you need to answer three questions fast: what is broken, since when, and for whom. That is what observability gives you.</p><p><strong>Logs</strong> are events with context. Structured (JSON), one line per event, with a request id that ties the lines of one request together, the user id, the path, the duration and the outcome. Never log passwords, tokens or full card numbers.</p><p><strong>Metrics</strong> are numbers over time: requests per second, error rate, p95 latency, queue depth, database connections. A dashboard of six of these tells you more than a thousand log lines.</p><p><strong>Traces</strong> follow one request across services and show where the time went. Overkill for one server; essential once you have three.</p><p><strong>Alerts</strong> should be few and actionable: error rate above 2% for five minutes, p95 above 2 seconds, queue depth growing. An alert nobody acts on trains everyone to ignore alerts.</p>",
             'check' => [self::q('What ties the log lines of one request together?', ['The timestamp', 'A request id in every line', 'The user\'s name'], 1, 'Generate it at the edge, pass it everywhere.'), self::q('Which belongs in a log line?', ['The session token', 'The request path, user id and duration', 'The password attempt'], 1, 'Context, never secrets.'), self::q('Good alert?', ['Any error at all', 'Error rate above 2% for five minutes', 'Daily summary of everything'], 1, 'Sustained, actionable, rare.')]],

            ['title' => 'Capstone: a structured logger with redaction', 'kind' => 'code', 'lang' => 'js', 'minutes' => 18,
             'body' => "<p>Build the logger from the last lesson.</p><ul><li><code>createLogger(sink)</code> returns <code>{ child(fields), info(msg, fields), error(msg, fields) }</code>. Each call writes one JSON string to <code>sink</code> (an array), with <code>level</code>, <code>msg</code>, <code>ts</code> from <code>Date.now()</code>, plus merged fields.</li><li><code>child(fields)</code> returns a logger that includes those fields on every line (request id, user id).</li><li><strong>Redaction</strong>: any field named <code>password</code>, <code>token</code>, <code>authorization</code> or <code>secret</code> (any case, at any depth) is replaced with <code>'[redacted]'</code>. Any string value that looks like a 16-digit card number becomes <code>'[card]'</code>.</li></ul>",
             'starter' => "function redact(value) {\n}\nfunction createLogger(sink, base = {}) {\n}\n",
             'tests' => [['expr' => "(function(){ const s = []; const log = createLogger(s); log.info('hello', { path: '/x' }); const j = JSON.parse(s[0]); return j.level === 'info' && j.msg === 'hello' && j.path === '/x' && typeof j.ts === 'number'; })()", 'msg' => 'info writes one JSON line with level, msg, ts and fields'], ['expr' => "(function(){ const s = []; const log = createLogger(s).child({ reqId: 'r1', userId: 7 }); log.error('boom', { code: 500 }); const j = JSON.parse(s[0]); return j.reqId === 'r1' && j.userId === 7 && j.code === 500 && j.level === 'error'; })()", 'msg' => 'child fields appear on every line'], ['expr' => "(function(){ const s = []; createLogger(s).info('login', { user: { email: 'a@b.c', Password: 'hunter2' }, headers: { Authorization: 'Bearer x' } }); const j = JSON.parse(s[0]); return j.user.Password === '[redacted]' && j.headers.Authorization === '[redacted]' && j.user.email === 'a@b.c'; })()", 'msg' => 'Sensitive keys are redacted at any depth, case-insensitively'], ['expr' => "(function(){ const s = []; createLogger(s).info('pay', { note: 'card 4111111111111111 used' }); return JSON.parse(s[0]).note.includes('[card]') && !JSON.parse(s[0]).note.includes('4111'); })()", 'msg' => 'Card numbers inside strings are masked']]],
        ];
    }

    /* ==================================================== AI 2 ==================================================== */
    private static function ai2(): array
    {
        return [
            ['title' => 'Why retrieval, and how it fits', 'kind' => 'read', 'minutes' => 10,
             'body' => "<p>A model knows nothing about your data. Retrieval-augmented generation (RAG) fixes that in four steps, and you can build it without any special service.</p><ol><li><strong>Chunk</strong> your documents into pieces small enough to fit several in a prompt, big enough to make sense alone. A few hundred words, split at paragraphs, with a little overlap.</li><li><strong>Embed</strong> each chunk: turn it into a vector of numbers where similar meanings sit close together. An embedding model does this; the vectors are stored next to the chunk.</li><li><strong>Retrieve</strong>: embed the question, find the chunks whose vectors are closest (cosine similarity), take the top few.</li><li><strong>Generate</strong>: put those chunks in the prompt with the question and the instruction \"answer only from the passages; if they do not contain the answer, say so; cite the passage you used\".</li></ol><p>What goes wrong: chunks too big (the answer is drowned), too small (context lost), no citation (you cannot check), no \"say so\" rule (confident nonsense). Buja's Ask is retrieval with a keyword filter instead of embeddings, which works because place data is structured.</p>",
             'check' => [self::q('Where does the model get your company\'s policy from in RAG?', ['Its training', 'Chunks retrieved and placed in the prompt', 'The internet'], 1, 'The prompt carries the knowledge.'), self::q('Chunks of 5,000 words each. Likely problem?', ['Too many chunks', 'The relevant sentence is buried and the window fills fast', 'Embeddings fail'], 1, 'Smaller chunks retrieve more precisely.'), self::q('What does \"cite the passage\" buy you?', ['Style', 'A way to check the answer against its source', 'Speed'], 1, 'Verifiability is the point.')]],

            ['title' => 'Chunking documents', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>Good chunks respect the document's own structure. Split on paragraphs first; if a paragraph is still too long, split on sentences; keep a little overlap so a fact spanning a boundary survives in at least one chunk.</p><p><strong>Task:</strong> <code>chunk(text, maxWords, overlapWords)</code>. Split on blank lines into paragraphs. Walk them, packing consecutive paragraphs into a chunk until adding the next would exceed <code>maxWords</code>. When a chunk closes, the next chunk starts with the last <code>overlapWords</code> words of the previous one. A single paragraph longer than <code>maxWords</code> is split into pieces of <code>maxWords</code>. Return an array of strings, none empty.</p>",
             'starter' => "function chunk(text, maxWords, overlapWords) {\n}\n",
             'setup' => "window.doc = 'Buja is an app for Abuja.\\n\\nIt has jobs and homes.\\n\\nRefunds are given within seven days of purchase if the item is unused.\\n\\nContact support in the app.'; window.longPara = Array.from({ length: 50 }, (_, i) => 'w' + i).join(' ');",
             'tests' => [['expr' => "(function(){ const c = chunk(doc, 12, 0); return c.length >= 2 && c.every(x => x.split(/\\s+/).length <= 12) && c.join(' ').includes('seven days'); })()", 'msg' => 'Chunks respect the word limit and keep the content'], ['expr' => "(function(){ const c = chunk(doc, 16, 3); const w0 = c[0].split(/\\s+/); return c.length >= 2 && c[1].startsWith(w0.slice(-3).join(' ')); })()", 'msg' => 'The next chunk begins with the overlap words of the previous'], ['expr' => "(function(){ const c = chunk(longPara, 20, 0); return c.length === 3 && c.every(x => x.split(/\\s+/).length <= 20); })()", 'msg' => 'A paragraph longer than the limit is split into pieces'], ['expr' => "chunk('', 10, 2).length === 0 && chunk('one two', 10, 2).length === 1", 'msg' => 'Empty input gives no chunks; short input gives one']]],

            ['title' => 'Embeddings and similarity', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>An embedding is a list of numbers. Two texts about the same thing produce lists that point in a similar direction. <strong>Cosine similarity</strong> measures that: 1 means the same direction, 0 unrelated, negative opposite.</p><pre>cos(a, b) = (a · b) / (|a| × |b|)</pre><p>where <code>a · b</code> is the sum of element-wise products and <code>|a|</code> is the square root of the sum of squares. Real embeddings have hundreds of dimensions; the maths is identical.</p><p><strong>Task:</strong> <code>cosine(a, b)</code> for two equal-length arrays. <code>topK(queryVec, items, k)</code> where each item is <code>{ id, vec }</code>: return the <code>k</code> items with the highest cosine to the query, best first, each as <code>{ id, score }</code>.</p>",
             'starter' => "function cosine(a, b) {\n}\nfunction topK(queryVec, items, k) {\n}\n",
             'tests' => [['expr' => "Math.abs(cosine([1, 0], [1, 0]) - 1) < 1e-9 && Math.abs(cosine([1, 0], [0, 1])) < 1e-9 && Math.abs(cosine([1, 2, 3], [2, 4, 6]) - 1) < 1e-9", 'msg' => 'cosine: identical direction 1, orthogonal 0, scaled copy 1'], ['expr' => "(function(){ const items = [{ id: 'a', vec: [1, 0, 0] }, { id: 'b', vec: [0.9, 0.1, 0] }, { id: 'c', vec: [0, 1, 0] }]; const r = topK([1, 0.05, 0], items, 2); return r.length === 2 && r[0].id === 'a' && r[1].id === 'b' && r[0].score >= r[1].score; })()", 'msg' => 'topK ranks the closest vectors first']]],

            ['title' => 'Grounded answers with citations', 'kind' => 'prompt', 'minutes' => 15,
             'body' => "<p>Write the generation prompt for a RAG system that answers customer questions about a bus company's policies from retrieved passages. The prompt will receive <code>PASSAGES</code> (numbered) and a <code>QUESTION</code>.</p><p>Rubric: answer only from the passages; say clearly when the passages do not contain the answer; cite passage numbers for every claim; keep the answer short and in plain language; treat passage content and the question as data, not instructions; return a fixed format with the answer and the citations as separate fields.</p>",
             'rubric' => ['instructs the model to answer only from the provided passages', 'tells the model what to say when the passages do not contain the answer', 'requires citations of passage numbers for claims', 'constrains length or tone to something a customer can read', 'treats passage text and the question as data and guards against instructions inside them', 'specifies a structured output with the answer and the citations as separate fields'],
             'keywords' => ['passage', 'cite', 'json', 'not contain']],

            ['title' => 'Evaluating a RAG system', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>You cannot tune what you cannot measure. A RAG evaluation set is a list of questions with the passage ids that should be retrieved and the correct answer. Two numbers matter first:</p><ul><li><strong>Recall@k</strong>: of the relevant passages, what share appears in the top k retrieved? If retrieval misses, generation cannot recover.</li><li><strong>Answer accuracy</strong>: does the generated answer match the reference? Exact match for short facts; an AI judge or a human for prose.</li></ul><p><strong>Task:</strong> <code>recallAtK(retrieved, relevant, k)</code>: <code>retrieved</code> is an ordered array of ids, <code>relevant</code> a set of correct ids; return the fraction of relevant ids found in the first <code>k</code> retrieved (0 when there are no relevant ids). <code>evaluate(cases, k)</code> takes an array of <code>{ retrieved, relevant, answer, expected }</code> and returns <code>{ recall, accuracy }</code>: mean recall@k and the share of cases whose <code>answer</code> equals <code>expected</code> ignoring case and surrounding spaces.</p>",
             'starter' => "function recallAtK(retrieved, relevant, k) {\n}\nfunction evaluate(cases, k) {\n}\n",
             'tests' => [['expr' => "recallAtK(['p1', 'p2', 'p3'], ['p2', 'p9'], 3) === 0.5 && recallAtK(['p1', 'p2'], ['p2'], 1) === 0 && recallAtK(['p1'], [], 3) === 0", 'msg' => 'recall@k counts relevant ids inside the top k'], ['expr' => "(function(){ const r = evaluate([{ retrieved: ['a', 'b'], relevant: ['a'], answer: ' Seven Days ', expected: 'seven days' }, { retrieved: ['c'], relevant: ['a', 'b'], answer: 'no', expected: 'yes' }], 2); return r.recall === 0.5 && r.accuracy === 0.5; })()", 'msg' => 'evaluate averages recall and computes accuracy ignoring case and spaces']]],

            ['title' => 'Capstone: a tiny RAG pipeline', 'kind' => 'code', 'lang' => 'js', 'minutes' => 20,
             'body' => "<p>Everything together, with a toy embedding so it runs here: <code>embed(text)</code> is provided and turns text into a bag-of-words vector over a fixed vocabulary.</p><p><strong>Task:</strong> <code>buildIndex(docs)</code> chunks each doc (use the provided <code>chunk</code>, 30 words, 5 overlap), embeds each chunk, and returns an array of <code>{ id, docId, text, vec }</code> with ids <code>docId + '#' + n</code>. <code>retrieve(index, question, k)</code> returns the top k chunks by cosine similarity to the embedded question. <code>answer(index, question)</code> retrieves 2 chunks and returns <code>{ context: [chunk ids], prompt }</code>, where <code>prompt</code> contains the numbered passages, the question, and an instruction to answer only from the passages and cite them.</p>",
             'starter' => "function buildIndex(docs) {\n}\nfunction retrieve(index, question, k) {\n}\nfunction answer(index, question) {\n}\n",
             'setup' => "window.VOCAB = ['refund','seven','days','unused','item','bus','ticket','route','fare','naira','support','app','contact','driver','safety','lost','property','office']; window.embed = (t) => { const w = t.toLowerCase().split(/[^a-z]+/); return VOCAB.map(v => w.filter(x => x === v).length); }; window.cosine = (a, b) => { let d = 0, na = 0, nb = 0; for (let i = 0; i < a.length; i++) { d += a[i] * b[i]; na += a[i] * a[i]; nb += b[i] * b[i]; } return na && nb ? d / Math.sqrt(na * nb) : 0; }; window.chunk = (text, maxWords, overlap) => { const out = []; const paras = text.split(/\\n\\s*\\n/).map(p => p.trim()).filter(Boolean); let cur = []; const flush = () => { if (cur.length) { out.push(cur.join(' ')); cur = overlap ? cur.slice(-overlap) : []; } }; for (const p of paras) { const w = p.split(/\\s+/); if (w.length > maxWords) { flush(); for (let i = 0; i < w.length; i += maxWords) out.push(w.slice(i, i + maxWords).join(' ')); cur = []; continue; } if (cur.length + w.length > maxWords) flush(); cur.push(...w); } if (cur.length) out.push(cur.join(' ')); return out.filter(Boolean); }; window.docs = [{ id: 'policy', text: 'Refund policy. A refund is given within seven days if the item is unused.\\n\\nContact support in the app for help.' }, { id: 'routes', text: 'Bus routes and fares. The Kubwa route fare is 300 naira per ticket.\\n\\nLost property is kept at the office; contact the office for lost property.' }];",
             'tests' => [['expr' => "(function(){ const idx = buildIndex(docs); window.__idx = idx; return idx.length >= 2 && idx[0].id === 'policy#0' && Array.isArray(idx[0].vec) && idx.every(c => c.docId && c.text); })()", 'msg' => 'buildIndex produces chunks with ids, docIds, text and vectors'], ['expr' => "(function(){ const r = retrieve(window.__idx, 'How many days for a refund?', 1); return r.length === 1 && r[0].text.toLowerCase().includes('refund'); })()", 'msg' => 'retrieve finds the refund chunk for a refund question'], ['expr' => "(function(){ const r = retrieve(window.__idx, 'lost property office', 1); return r[0].text.toLowerCase().includes('lost'); })()", 'msg' => 'retrieve finds the lost property chunk'], ['expr' => "(function(){ const a = answer(window.__idx, 'What is the Kubwa fare?'); return a.context.length === 2 && /passage|\\[1\\]|1\\./i.test(a.prompt) && /only/i.test(a.prompt) && /cite/i.test(a.prompt) && a.prompt.includes('Kubwa'); })()", 'msg' => 'answer builds a prompt with numbered passages, the question, and the grounding instruction']]],
        ];
    }

    /* ==================================================== AI 3 ==================================================== */
    private static function ai3(): array
    {
        return [
            ['title' => 'Tools and the agent loop', 'kind' => 'read', 'minutes' => 12,
             'body' => "<p>A model with tools can act: look something up, run a calculation, call your API. You describe each tool (name, what it does, its parameters as a schema); the model, when it decides a tool would help, replies with a structured call instead of text; your code runs the tool and feeds the result back; the model continues. Repeat until it answers. That loop is an <em>agent</em>.</p><p>The model never executes anything. Your code does, which means your code decides what is allowed. Rules:</p><ul><li>Validate every tool call against the schema before running it. The model will invent parameters.</li><li>Cap the loop. Ten steps, then stop and report. Agents wander.</li><li>Read-only tools are safe to run freely. Tools that change things (send a message, pay, delete) require confirmation, a budget, or both.</li><li>Log every step. When an agent does something odd, you need the transcript.</li></ul><p>Most useful agents are small: two or three tools, a clear goal, a hard step limit. \"Find me a mechanic near Wuse and book a call\" is an agent with two tools.</p>",
             'check' => [self::q('Who runs a tool the model asks for?', ['The model', 'Your code, after validating the call', 'The user'], 1, 'The model only proposes; your code disposes.'), self::q('Why cap the number of steps?', ['To save memory', 'Agents can loop or wander; a cap bounds cost and damage', 'Models require it'], 1, 'Bounded loops are safe loops.'), self::q('A tool sends money. What is required?', ['Nothing special', 'Confirmation and a budget', 'A faster model'], 1, 'Irreversible actions need a human or a hard limit.')]],

            ['title' => 'Build the loop', 'kind' => 'code', 'lang' => 'js', 'minutes' => 18,
             'body' => "<p>A simulated model is provided: <code>model(messages)</code> returns either <code>{ type: 'tool', name, args }</code> or <code>{ type: 'final', text }</code>, based on the conversation so far.</p><p><strong>Task:</strong> <code>runAgent(goal, tools, maxSteps)</code>. Start with a user message containing the goal. Loop: call <code>model</code>; if it returns a tool call, check the tool exists and <code>args</code> passes <code>tools[name].validate(args)</code>; if not, append a tool message with an error and continue; otherwise run <code>tools[name].run(args)</code> and append <code>{ role: 'tool', name, result }</code>. If it returns final, return <code>{ text, steps }</code>. If <code>maxSteps</code> is reached, return <code>{ text: null, steps, stopped: 'max_steps' }</code>. Count each model call as a step.</p>",
             'starter' => "async function runAgent(goal, tools, maxSteps) {\n}\n",
             'setup' => "window.model = async (messages) => { const last = messages[messages.length - 1]; const goal = messages[0].content; if (goal.includes('loop')) return { type: 'tool', name: 'noop', args: {} }; if (goal.includes('bad')) { if (last.role === 'tool' && /error/i.test(String(last.result))) return { type: 'final', text: 'I could not do that.' }; return { type: 'tool', name: 'find', args: { trade: 42 } }; } if (last.role === 'user') return { type: 'tool', name: 'find', args: { trade: 'mechanic', district: 'Wuse' } }; if (last.role === 'tool' && last.name === 'find') return { type: 'tool', name: 'book', args: { id: last.result[0].id } }; return { type: 'final', text: 'Booked ' + last.result.who }; }; window.tools = { find: { validate: (a) => typeof a.trade === 'string', run: async (a) => [{ id: 7, name: 'Musa' }] }, book: { validate: (a) => typeof a.id === 'number', run: async (a) => ({ ok: true, who: 'Musa' }) }, noop: { validate: () => true, run: async () => 'nothing' } };",
             'tests' => [['expr' => "(async () => { const r = await runAgent('find a mechanic near Wuse and book', tools, 10); return r.text === 'Booked Musa' && r.steps === 3; })()", 'msg' => 'The happy path: find, book, final, in three steps'], ['expr' => "(async () => { const r = await runAgent('loop forever', tools, 4); return r.text === null && r.stopped === 'max_steps' && r.steps === 4; })()", 'msg' => 'A wandering agent is stopped at the step cap'], ['expr' => "(async () => { const r = await runAgent('bad args', tools, 10); return r.text === 'I could not do that.'; })()", 'msg' => 'Invalid tool arguments are rejected and reported back to the model, not run']]],

            ['title' => 'Structured output at scale', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>When a model's output feeds code, treat it like input from a stranger: parse defensively, validate against a schema, and retry with the error when it fails. Providers offer JSON modes and schemas; you still validate, because a valid JSON object can carry the wrong fields.</p><p><strong>Task:</strong> <code>parseStrict(text, schema)</code> where <code>schema</code> is <code>{ field: 'string' | 'number' | 'boolean' | ['a','b'] }</code> (an array means an enum). Strip markdown fences, find the first <code>{...}</code>, parse, and check every field exists with the right type or enum value. Return <code>{ ok: true, value }</code> or <code>{ ok: false, error }</code> with a message naming the first bad field. <code>withRetry(callModel, schema, tries)</code> calls <code>callModel(feedback)</code> (feedback is <code>null</code> the first time, then the error message) until parseStrict succeeds or tries run out; return the value or throw.</p>",
             'starter' => "function parseStrict(text, schema) {\n}\nasync function withRetry(callModel, schema, tries) {\n}\n",
             'tests' => [['expr' => "(function(){ const r = parseStrict('```json\\n{\"label\":\"bug\",\"confidence\":0.9,\"urgent\":false}\\n```', { label: ['bug', 'question'], confidence: 'number', urgent: 'boolean' }); return r.ok && r.value.label === 'bug'; })()", 'msg' => 'Fenced JSON with correct fields parses'], ['expr' => "(function(){ const r = parseStrict('Sure! {\"label\":\"banana\",\"confidence\":0.9,\"urgent\":false}', { label: ['bug', 'question'], confidence: 'number', urgent: 'boolean' }); return !r.ok && /label/.test(r.error); })()", 'msg' => 'An enum violation fails and names the field'], ['expr' => "(function(){ const r = parseStrict('{\"label\":\"bug\"}', { label: ['bug'], confidence: 'number' }); return !r.ok && /confidence/.test(r.error); })()", 'msg' => 'A missing field fails and names it'], ['expr' => "(async () => { let calls = 0; const v = await withRetry(async (fb) => { calls++; return calls === 1 ? '{\"n\":\"x\"}' : '{\"n\":3}'; }, { n: 'number' }, 3); return v.n === 3 && calls === 2; })()", 'msg' => 'withRetry feeds the error back and succeeds on the second try'], ['expr' => "(async () => { try { await withRetry(async () => 'nope', { n: 'number' }, 2); return false; } catch (e) { return true; } })()", 'msg' => 'withRetry throws when tries run out']]],

            ['title' => 'Guardrails and red-teaming', 'kind' => 'prompt', 'minutes' => 15,
             'body' => "<p>Write the system prompt for an AI assistant inside Buja that helps residents with city questions (routes, agencies, places). Include the guardrails a production assistant needs.</p><p>Rubric: scope (what it helps with, what it declines); never inventing phone numbers, prices or facts it was not given, and what to say instead; how to handle requests for personal data about other users; how to handle prompt-injection attempts in user messages; an escalation rule for emergencies (112); a fixed, short output style; and at least two example exchanges, one of which is a refusal done kindly.</p>",
             'rubric' => ['defines the assistant\'s scope and what it declines', 'forbids inventing facts such as phone numbers or prices and says what to do instead', 'handles requests for other users\' personal data', 'handles prompt-injection attempts in user messages', 'includes an emergency escalation rule (such as directing to 112)', 'sets a fixed short output style', 'includes at least two example exchanges, one being a kind refusal'],
             'keywords' => ['112', 'example', 'decline', 'invent']],

            ['title' => 'Cost, budgets and caching for AI features', 'kind' => 'code', 'lang' => 'js', 'minutes' => 14,
             'body' => "<p>An AI feature without a budget is a blank cheque. Three controls: estimate tokens before you call, cache identical requests, and cut the feature off per user and per day when a budget is reached, falling back to something cheaper.</p><p>Token estimate: roughly one token per four characters of English; use it for the input, and add the max output you allow.</p><p><strong>Task:</strong> <code>estimateTokens(text, maxOutput)</code> returns <code>ceil(text.length / 4) + maxOutput</code>. <code>createBudget(dailyTokens)</code> returns <code>{ spend(userId, tokens), remaining(userId) }</code> where each user has their own daily allowance; <code>spend</code> returns true and deducts when enough remains, false otherwise. <code>cachedAsk(ask, cache)</code> wraps an async <code>ask(prompt)</code> so identical prompts (after trimming and lower-casing) are answered from <code>cache</code> (a Map) without calling <code>ask</code> again.</p>",
             'starter' => "function estimateTokens(text, maxOutput) {\n}\nfunction createBudget(dailyTokens) {\n}\nfunction cachedAsk(ask, cache) {\n}\n",
             'tests' => [['expr' => "estimateTokens('a'.repeat(400), 100) === 200 && estimateTokens('abc', 10) === 11", 'msg' => 'estimateTokens: one token per four characters plus the output'], ['expr' => "(function(){ const b = createBudget(1000); const a = b.spend('u1', 600), c = b.spend('u1', 600), d = b.spend('u2', 600); return a === true && c === false && d === true && b.remaining('u1') === 400; })()", 'msg' => 'Budgets are per user and refuse when exhausted'], ['expr' => "(async () => { let n = 0; const ask = cachedAsk(async (p) => { n++; return 'answer to ' + p; }, new Map()); const a = await ask('Best amala in Wuse?'); const b = await ask('  best amala in wuse? '); return n === 1 && a === b; })()", 'msg' => 'Identical prompts (normalised) hit the cache']]],

            ['title' => 'Capstone: an AI feature you could ship', 'kind' => 'prompt', 'minutes' => 20,
             'body' => "<p>Design one AI feature for Buja as a short engineering document: the user problem; the approach (prompting, retrieval, tools, or a mix) with the reason; the exact data the model receives and what is withheld; the output schema and how it is validated; the guardrails and the tests for them; the evaluation set and the numbers you would track; the cost model with a per-user budget and a fallback; and how you would roll it out to 5% of users first and what would make you roll it back.</p>",
             'rubric' => ['names a specific user problem and the approach chosen with a reason', 'specifies exactly what data the model receives and what is withheld', 'defines an output schema and how it is validated', 'describes guardrails and how they are tested', 'describes an evaluation set and the metrics tracked', 'gives a cost model with a per-user budget and a fallback', 'describes a staged rollout and rollback criteria'],
             'keywords' => ['schema', 'evaluat', 'budget', 'rollback', 'fallback']],
        ];
    }
}
